name: Clojars Deploy

on: push

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: lein test
      - name: Deploy
        env:
          CLOJARS_USER: ${{ secrets.CLOJARS_USER }}
          CLOJARS_PASS: ${{ secrets.CLOJARS_PASS }}
        run: lein deploy

